force-app/main/default/objects/Customer_Product_Info_Config__mdt/Customer_Product_Info_Config__mdt.object-meta.xml
<CustomObject>
    <description>Customer product information related to country</description>
    <label>Customer Product Info Config</label>
    <pluralLabel>Customer Product Info Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Customer_Product_Info_Config__mdt/fields/ATM_Fee__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee__c</fullName>
    <description>Customer product  ATM Fee in Other Currencies</description>
    <label>ATM Fee</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Info_Config__mdt/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <description>Card Replacement Cost per each product</description>
    <label>Card Replacement Cost</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Info_Config__mdt/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>Country Code for customer product</description>
    <label>Country Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Info_Config__mdt/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <description>Name of the country related to product</description>
    <label>Home Country</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Info_Config__mdt/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <description>Currency ISO Code</description>
    <label>Currency Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Info_Config__mdt/fields/Currency_Symbol__c.field-meta.xml
<CustomField>
    <fullName>Currency_Symbol__c</fullName>
    <description>Currency used per each Country</description>
    <label>Currency Symbol</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Info_Config__mdt/fields/Is_Free_ATM_Fee__c.field-meta.xml
<CustomField>
    <fullName>Is_Free_ATM_Fee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Free ATM Fee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Info_Config__mdt/fields/Is_Not_Applicable_Monthly_Cost__c.field-meta.xml
<CustomField>
    <fullName>Is_Not_Applicable_Monthly_Cost__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the cost per calendar month is not applicable</description>
    <label>Is Not Applicable Monthly Cost</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Info_Config__mdt/fields/Monthly_Cost__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Cost__c</fullName>
    <description>Customer product cost per calendar month.</description>
    <label>Cost per Calendar Month</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Product_Info_Config__mdt/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Customer product</description>
    <label>Plan Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Selectors/CustomerProductInfoConfigSelector.cls
/**
 * Selector class for retrieving and managing Customer_Product_Info_Config__mdt metadata.
 * Implements the IGenericMetadataSelector interface to provide standardized selection logic.
 *
 * This class is designed to encapsulate queries and operations related to Customer_Product_Info_Config__mdt records,
 * ensuring consistent access patterns and sharing rules.
 *
 * @author Carlos Martínez Pérez
 * @created 2025-08-01
 */
global virtual with sharing class CustomerProductInfoConfigSelector implements IGenericMetadataSelector {

    // fields to query from metadata
    public static final List<String> METADATA_CONFIG_FIELD = new List<String>{
        'MasterLabel',
        'Product__c',
        'Country_Name__c',
        'Country_Code__c',
        'Currency_Code__c',
        'Currency_Symbol__c',
        'Monthly_Cost__c',
        'Is_Not_Applicable_Monthly_Cost__c',
        'ATM_Fee__c',
        'Is_Free_ATM_Fee__c',
        'Card_Replacement_Cost__c'
    };
   
    /**
     * Retrieves a Customer_Product_Info_Config__mdt record by its DeveloperName.
     *
     * @param developerName The DeveloperName of the Customer_Product_Info_Config__mdt record to retrieve.
     * @return The Customer_Product_Info_Config__mdt record matching the specified DeveloperName, or null if not found.
     */
    public Customer_Product_Info_Config__mdt getByDeveloperName(String developerName) {
        List<Customer_Product_Info_Config__mdt> results = (List<Customer_Product_Info_Config__mdt>) new QueryBuilder()
            .setSObject('Customer_Product_Info_Config__mdt')
            .selectFields(METADATA_CONFIG_FIELD)
            .addWhereClause('DeveloperName = \'' + developerName + '\'')
            .setLimit(1)
            .execute();
        return results.isEmpty() ? null : results[0];
    }


    
    /**
     * Retrieves the Customer Product Info Config custom metadata record for a given product and country.
     *
     * @param product The name or identifier of the product.
     * @param country The name or code of the country.
     * @return Customer_Product_Info_Config__mdt The matching custom metadata record, or null if not found.
     */
    global virtual Customer_Product_Info_Config__mdt getProductInfoByProductCountry(String product, String country) {

        List<Customer_Product_Info_Config__mdt> configs = (List<Customer_Product_Info_Config__mdt>) new QueryBuilder()
            .setSObject('Customer_Product_Info_Config__mdt')
            .selectFields(METADATA_CONFIG_FIELD)
            .addWhereClause('Product__c = \'' + product + '\'')
            .addWhereClause('Country_Name__c = \'' + country + '\'')
            .setLimit(1)
            .execute();

        if (!configs.isEmpty()) {
            return configs[0];
        }
        return null;
    }
}