force-app/main/default/objects/Contact/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>Id used for external system to access contact record</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>Contact Legal Country</description>
    <label>Home Country</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Customer&apos;s product</description>
    <label>Product</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/builders/ContactBuilder.cls
/**
 * Builder class for creating Contact records .
 * Provides methods to set relevant fields.
 *
 * @author Carlos Martínez Pérez
 * @created 2025-08-03
 */
public class ContactBuilder {
    private Contact contact;

    public ContactBuilder() {
        contact = new Contact();
    }

    public ContactBuilder withId(String Id) {
        contact.Id = Id;
        return this;
    }

    public ContactBuilder withProduct(String product) {
        contact.Product__c = product;
        return this;
    }

    public ContactBuilder withHomeCountry(String country) {
        contact.Home_Country__c = country;
        return this;
    }

    public ContactBuilder withExternalId(String externalId) {
        contact.External_Id__c = externalId;
        return this;
    }

    public Contact build() {
        return contact;
    }
}